### ISSUE TITLE
Po přechodu do aplikace přes notifikaci přehrávání někdy spadne.

### ISSUE THREAD

**Issue by rzeh4n** [moravianlibrary/kramerius-for-android#221]
FATAL EXCEPTION: AsyncTask #1
 Process: cz.mzk.kramerius.app, PID: 27167
 java.lang.RuntimeException: An error occured while executing doInBackground()
     at android.os.AsyncTask$3.done(AsyncTask.java:300)
     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:841)
  Caused by: java.lang.VerifyError: org/dom4j/xpath/DefaultXPath
     at org.dom4j.DocumentFactory.createXPath(DocumentFactory.java:230)
     at org.dom4j.tree.AbstractNode.createXPath(AbstractNode.java:207)
     at org.dom4j.tree.AbstractNode.selectSingleNode(AbstractNode.java:183)
     at cz.mzk.kramerius.app.xml.ModsParser.getMetadata(ModsParser.java:41)
     at cz.mzk.kramerius.app.api.K5ConnectorImplHttpUrlConnection.getModsMetadata(K5ConnectorImplHttpUrlConnection.java:592)
     at cz.mzk.kramerius.app.ui.SoundRecordingActivity$2.doInBackground(SoundRecordingActivity.java:161)
     at cz.mzk.kramerius.app.ui.SoundRecordingActivity$2.doInBackground(SoundRecordingActivity.java:148)
     at android.os.AsyncTask$2.call(AsyncTask.java:288)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
     at java.lang.Thread.run(Thread.java:841)

**Comment by rzeh4n** [comment]
Nepodařilo se mi reprodukovat na žádné z volně dostupných nahrávek v MZK. Testoval jsem to s vypnutím nového cachování MODS parsovaných metadat.
Asi bylo vyřešeno nahrazením verze Jaxenu, nebo je to způsobeno chybou metadat, která byla jsou už opravena.
Pokud se to objeví znovu, prosím o upřesnění nahrávky.
